// src/data/pizzaMap.ts

export const pizzaMap: Record<string, { name: string; price: string }> = {
"hawaiian_m": { name: "The Hawaiian Pizza", price: "13.25" },
"classic_dlx_m": { name: "The Classic Deluxe Pizza", price: "16" },
"ital_supr_m": { name: "The Italian Supreme Pizza", price: "16.5" },
"mexicana_m": { name: "The Mexicana Pizza", price: "16" },
"thai_ckn_m": { name: "The Thai Chicken Pizza", price: "16.75" },
"prsc_argla_m": { name: "The Prosciutto and Arugula Pizza", price: "16.5" },
"bbq_ckn_m": { name: "The Barbecue Chicken Pizza", price: "16.75" },
"the_greek_m": { name: "The Greek Pizza", price: "16" },
"spinach_supr_m": { name: "The Spinach Supreme Pizza", price: "16.5" },
"green_garden_m": { name: "The Green Garden Pizza", price: "16" },
"ital_cpcllo_m": { name: "The Italian Capocollo Pizza", price: "16" },
"spicy_ital_m": { name: "The Spicy Italian Pizza", price: "16.5" },
"spin_pesto_m": { name: "The Spinach Pesto Pizza", price: "16.5" },
"veggie_veg_m": { name: "The Vegetables + Vegetables Pizza", price: "16" },
"southw_ckn_m": { name: "The Southwest Chicken Pizza", price: "16.75" },
"cali_ckn_m": { name: "The California Chicken Pizza", price: "16.75" },
"pepperoni_m": { name: "The Pepperoni Pizza", price: "12.5" },
"ckn_pesto_m": { name: "The Chicken Pesto Pizza", price: "16.75" },
"soppressata_m": { name: "The Soppressata Pizza", price: "16.5" },
"four_cheese_m": { name: "The Four Cheese Pizza", price: "14.75" },
"napolitana_m": { name: "The Napolitana Pizza", price: "16" },
"calabrese_m": { name: "The Calabrese Pizza", price: "16.25" },
"ital_veggie_m": { name: "The Italian Vegetables Pizza", price: "16.75" },
"mediterraneo_m": { name: "The Mediterranean Pizza", price: "16" },
"peppr_salami_m": { name: "The Pepper Salami Pizza", price: "16.5" },
"spinach_fet_m": { name: "The Spinach and Feta Pizza", price: "16" },
"sicilian_m": { name: "The Sicilian Pizza", price: "16.25" },
"ckn_alfredo_m": { name: "The Chicken Alfredo Pizza", price: "16.75" },
"pep_msh_pep_m": { name: "The Pepperoni, Mushroom, and Peppers Pizza", price: "14.5" },
}
