// src/data/pizzaMap.ts

export const pizzaMap: Record<string, { name: string; price: string }> = {
    "hawaiian_m": { name: "The Hawaiian Pizza", price: "13.25" },
    "hawaiian_l": { name: "The Hawaiian Pizza", price: "16.5" },
    "hawaiian_s": { name: "The Hawaiian Pizza", price: "10.5" },
    "classic_dlx_m": { name: "The Classic Deluxe Pizza", price: "16" },
    "five_cheese_l": { name: "The Five Cheese Pizza", price: "18.5" },
    "ital_supr_s": { name: "The Italian Supreme Pizza", price: "12.5" },
    "ital_supr_m": { name: "The Italian Supreme Pizza", price: "16.5" },
    "ital_supr_l": { name: "The Italian Supreme Pizza", price: "20.75" },
    "mexicana_s": { name: "The Mexicana Pizza", price: "12" },
    "mexicana_l": { name: "The Mexicana Pizza", price: "20.25" },
    "mexicana_m": { name: "The Mexicana Pizza", price: "16" },
    "thai_ckn_s": { name: "The Thai Chicken Pizza", price: "12.75" },
    "thai_ckn_m": { name: "The Thai Chicken Pizza", price: "16.75" },
    "thai_ckn_l": { name: "The Thai Chicken Pizza", price: "20.75" },
    "prsc_argla_s": { name: "The Prosciutto and Arugula Pizza", price: "12.5" },
    "prsc_argla_m": { name: "The Prosciutto and Arugula Pizza", price: "16.5" },
    "prsc_argla_l": { name: "The Prosciutto and Arugula Pizza", price: "20.75" },
    "bbq_ckn_m": { name: "The Barbecue Chicken Pizza", price: "16.75" },
    "bbq_ckn_l": { name: "The Barbecue Chicken Pizza", price: "20.75" },
    "bbq_ckn_s": { name: "The Barbecue Chicken Pizza", price: "12.75" },
    "the_greek_xl": { name: "The Greek Pizza", price: "25.5" },
    "the_greek_xxl": { name: "The Greek Pizza", price: "35.95" },
    "the_greek_l": { name: "The Greek Pizza", price: "20.5" },
    "the_greek_m": { name: "The Greek Pizza", price: "16" },
    "the_greek_s": { name: "The Greek Pizza", price: "12" },
    "spinach_supr_l": { name: "The Spinach Supreme Pizza", price: "20.75" },
    "spinach_supr_m": { name: "The Spinach Supreme Pizza", price: "16.5" },
    "spinach_supr_s": { name: "The Spinach Supreme Pizza", price: "12.5" },
    "green_garden_m": { name: "The Green Garden Pizza", price: "16" },
    "green_garden_l": { name: "The Green Garden Pizza", price: "20.25" },
    "green_garden_s": { name: "The Green Garden Pizza", price: "12" },
    "ital_cpcllo_s": { name: "The Italian Capocollo Pizza", price: "12" },
    "ital_cpcllo_m": { name: "The Italian Capocollo Pizza", price: "16" },
    "ital_cpcllo_l": { name: "The Italian Capocollo Pizza", price: "20.5" },
    "spicy_ital_m": { name: "The Spicy Italian Pizza", price: "16.5" },
    "spicy_ital_s": { name: "The Spicy Italian Pizza", price: "12.5" },
    "spicy_ital_l": { name: "The Spicy Italian Pizza", price: "20.75" },
    "spin_pesto_m": { name: "The Spinach Pesto Pizza", price: "16.5" },
    "spin_pesto_s": { name: "The Spinach Pesto Pizza", price: "12.5" },
    "spin_pesto_l": { name: "The Spinach Pesto Pizza", price: "20.75" },
    "veggie_veg_s": { name: "The Vegetables + Vegetables Pizza", price: "12" },
    "veggie_veg_m": { name: "The Vegetables + Vegetables Pizza", price: "16" },
    "veggie_veg_l": { name: "The Vegetables + Vegetables Pizza", price: "20.25" },
    "southw_ckn_m": { name: "The Southwest Chicken Pizza", price: "16.75" },
    "southw_ckn_s": { name: "The Southwest Chicken Pizza", price: "12.75" },
    "southw_ckn_l": { name: "The Southwest Chicken Pizza", price: "20.75" },
    "cali_ckn_l": { name: "The California Chicken Pizza", price: "20.75" },
    "cali_ckn_s": { name: "The California Chicken Pizza", price: "12.75" },
    "cali_ckn_m": { name: "The California Chicken Pizza", price: "16.75" },
    "pepperoni_s": { name: "The Pepperoni Pizza", price: "9.75" },
    "pepperoni_m": { name: "The Pepperoni Pizza", price: "12.5" },
    "pepperoni_l": { name: "The Pepperoni Pizza", price: "15.25" },
    "ckn_pesto_l": { name: "The Chicken Pesto Pizza", price: "20.75" },
    "ckn_pesto_s": { name: "The Chicken Pesto Pizza", price: "12.75" },
    "ckn_pesto_m": { name: "The Chicken Pesto Pizza", price: "16.75" },
    "big_meat_s": { name: "The Big Meat Pizza", price: "12" },
    "soppressata_s": { name: "The Soppressata Pizza", price: "12.5" },
    "soppressata_m": { name: "The Soppressata Pizza", price: "16.5" },
    "soppressata_l": { name: "The Soppressata Pizza", price: "20.75" },
    "four_cheese_l": { name: "The Four Cheese Pizza", price: "17.95" },
    "four_cheese_m": { name: "The Four Cheese Pizza", price: "14.75" },
    "napolitana_m": { name: "The Napolitana Pizza", price: "16" },
    "napolitana_l": { name: "The Napolitana Pizza", price: "20.5" },
    "napolitana_s": { name: "The Napolitana Pizza", price: "12" },
    "calabrese_s": { name: "The Calabrese Pizza", price: "12.25" },
    "calabrese_l": { name: "The Calabrese Pizza", price: "20.25" },
    "calabrese_m": { name: "The Calabrese Pizza", price: "16.25" },
    "ital_veggie_m": { name: "The Italian Vegetables Pizza", price: "16.75" },
    "ital_veggie_l": { name: "The Italian Vegetables Pizza", price: "21" },
    "ital_veggie_s": { name: "The Italian Vegetables Pizza", price: "12.75" },
    "mediterraneo_l": { name: "The Mediterranean Pizza", price: "20.25" },
    "mediterraneo_s": { name: "The Mediterranean Pizza", price: "12" },
    "mediterraneo_m": { name: "The Mediterranean Pizza", price: "16" },
    "peppr_salami_s": { name: "The Pepper Salami Pizza", price: "12.5" },
    "peppr_salami_l": { name: "The Pepper Salami Pizza", price: "20.75" },
    "peppr_salami_m": { name: "The Pepper Salami Pizza", price: "16.5" },
    "spinach_fet_s": { name: "The Spinach and Feta Pizza", price: "12" },
    "spinach_fet_m": { name: "The Spinach and Feta Pizza", price: "16" },
    "spinach_fet_l": { name: "The Spinach and Feta Pizza", price: "20.25" },
    "sicilian_s": { name: "The Sicilian Pizza", price: "12.25" },
    "sicilian_m": { name: "The Sicilian Pizza", price: "16.25" },
    "sicilian_l": { name: "The Sicilian Pizza", price: "20.25" },
    "ckn_alfredo_m": { name: "The Chicken Alfredo Pizza", price: "16.75" },
    "ckn_alfredo_l": { name: "The Chicken Alfredo Pizza", price: "20.75" },
    "ckn_alfredo_s": { name: "The Chicken Alfredo Pizza", price: "12.75" },
    "pep_msh_pep_m": { name: "The Pepperoni, Mushroom, and Peppers Pizza", price: "14.5" },
    "pep_msh_pep_s": { name: "The Pepperoni, Mushroom, and Peppers Pizza", price: "11" },
    "pep_msh_pep_l": { name: "The Pepperoni, Mushroom, and Peppers Pizza", price: "17.5" },
    "brie_carre_s": { name: "The Brie Carre Pizza", price: "23.65" },
}